### ISSUE TITLE
index is undefined in config.index

### ISSUE THREAD

**Issue by dotnetCarpenter** [smikes/npm-kludge-search#10]
I just tried `npm-kludge-search` for the first time on a [cloud9](https://c9.io/) instance.
```shell
npm-kludge-search headers

/home/ubuntu/.nvm/v0.10.35/lib/node_modules/npm-kludge-search/node_modules/pure-fts/lib/findIndex.js:10
    bag_idx = bsearch(config.index, name, function (a, b) {
                            ^
TypeError: Cannot read property 'index' of undefined
    at findIndex (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/npm-kludge-search/node_modules/pure-fts/lib/findIndex.js:10:29)
    at Purefts.search (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/npm-kludge-search/node_modules/pure-fts/lib/search.js:29:5)
    at searchDb (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/npm-kludge-search/lib/search.js:19:8)
    at /home/ubuntu/.nvm/v0.10.35/lib/node_modules/npm-kludge-search/lib/main.js:74:9
    at /home/ubuntu/.nvm/v0.10.35/lib/node_modules/npm-kludge-search/lib/makeDb.js:14:9
    at /home/ubuntu/.nvm/v0.10.35/lib/node_modules/npm-kludge-search/node_modules/pure-fts/lib/thaw.js:137:9
    at done (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/npm-kludge-search/node_modules/pure-fts/node_modules/async/lib/async.js:132:19)
    at /home/ubuntu/.nvm/v0.10.35/lib/node_modules/npm-kludge-search/node_modules/pure-fts/node_modules/async/lib/async.js:32:16
    at /home/ubuntu/.nvm/v0.10.35/lib/node_modules/npm-kludge-search/node_modules/pure-fts/lib/thaw.js:123:24
    at /home/ubuntu/.nvm/v0.10.35/lib/node_modules/npm-kludge-search/node_modules/pure-fts/lib/thaw.js:91:28
```

**Comment by mralexgray** [comment]
+1  same on a fresh install of Mac OS X 10.10.5

**Comment by smikes** [comment]
I can reproduce this with `npm test`.  Not sure how I did that, thanks for the bug report.

**Comment by smikes** [comment]
Turns out I was halfway through a change where instead of making each user rebuild the index on install, I would download it from github pages.  Never committed the last step.

Please try upgrading to latest (2.9.5), you should get an index downloaded.

**Comment by dotnetCarpenter** [comment]
@smikes thanks. Just tested 2.9.5 on ubuntu and it works
